version: '3.6'
services:
  ultraviolet:
    build:
      context: ./src
    depends_on:
      - db
  db:
    image: mariadb
    volumes:
      - ~/uvdb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
